import Head from "next/head";
import { motion } from "framer-motion";
export default function Home() {
  return (
    <motion.div
      className="text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-100 px-48"
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.75, ease: "easeOut" }}
    >
      <Head>
        <title>Page App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-48 p-2 overflow-hidden">
          <h1 className="text-6xl  text-center  lg:text-9xl">Cool Stuff</h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Video</h2>
            <h2>Firm</h2>
            <h2>1902</h2>
          </div>
          <div>
            <h3>We make memories.</h3>
            <h3> Just they way you love it</h3>
            <h3>Click for cool transition</h3>
          </div>
        </div>
      </main>
    </motion.div>
  );
}
